language: go

go:
- 1.11.x
- 1.12.x
- master

os:
  - linux
  - osx

before_script:
  - go get gopkg.in/yaml.v2

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  skip_cleanup: true
  file: "k8s"
  on:
    repo: pathristikon/k8s-applier
    tags: true
    go: 1.12.x
    os: linux
