language: go
go:
- '1.10'
- 1.11.x
deploy:
  provider: releases
  file:
  - k8s
  token: kEOwAcbAp9giqFRF7NzchCCLIEb+USXLvGH7P8u3gxuddFHRUlSpk3+qRzOsMjiT43fi4OP1dmPtBUwwOl0g/0chNEjyP62lYhjB9NB7l2tO+Txqw2vtD+JfemOQLIccgHe3nOMClswaBobl46eGe3/fzFvi3sVCGX09hHDOZ30aA/VnqfX6ebWJkOLTxx+C/0DMmOGpN9usTzJ6BwcVrDnnQ+hVN/hZhUizHrc2Zr2g9wiIZ+u+xRU5OkIUNQ6dcPuUg2mgDze6RCwC4OwLL32DjHpJtDD36kBth1L8RcYS2S1QyBp+biHtQfCJuj6UxACqv2x9/kz3L8FF3FMeGnf4io+SG2cwUcdsKwkHQ3r8qg7fNliI9ZtcI22qyZm/TL7HoHqh2UUkg+QJDHMqdbzdHA5qKQ1ex6wO2+JRGy0P+rj6tooNgfjYbOCGdx075RzdaLmfzeVn4zAwxcqJr11pYI0FCPC51dJUo5p5X7zps6ducCRyxs2VT765SApuNQweJgG6qtmDstqXnvYlwNSn3EJtRXXW2dp3URGZEPK0HCxyPMBOe5dEN6x4QYMPyqk7uR8R6OIuQYiZScwvKImpRpKrHYfcyWY6b4Fu3+7on2ASMIH2tn+MsJsP6gwBmslJhZ1GfE4iqWe6xrnnP0pgVBoF6laJNmT/+23Fyw4=
  on:
    repo: pathristikon/k8s-applier
    tags: false
    go: 1.11.x
