language: go
go:
- 1.11.x
- 1.12.x
- master

os:
  - linux
  - osx

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  cleanup: false
  file: "k8s"
  on:
    repo: pathristikon/k8s-applier
    tags: true
    go: 1.12.x
    os: linux
