language: go
go:
- '1.10'
- 1.11.x
deploy:
  provider: releases
  api_key:
    secure: RwNSe6z0jb/QaKDSVYcTEB5RqejPDuUWEGHvXZ3yFPlEW13xnCT53EydcVXK14hmqbn72cHO1ocs6UQP+YckGu1TocFRnFIz29tJJcHREZJC81JkTc1LiNSoGooQ/Eu14DZP6e8kUeJEmQzkckBfsyKDrIIz9VL3gU1QgDHdq+x7cqYJcT5F7pdrdZ4f/UhZI0H0kZM5hZKF6uFaieRH3+4Gpxwctd9BYiuI2BhU5VFHR+MV9RuKny8R8TTJVrbHeTHGA2NKTUa1pLeNvEX1xRYeYCZ96DScRzkMxDmxKLq2Q4hc4VbHuLyjYJsDOPN55g3fIcm7aWxBBHT/TX5rn4ZIj2TneGUPm1TErzLifYrN3Bng2954Fpv6NGJuMSCC5kKcQrHiPqjhILXN6HtKCegAC+BzG3G+iW8OuE9whjkj4c79tzKmnl6uwWc0JaU8r7H+pTra46lEmst96FIj4mrTrdMWN4xlJXzw52QzeWNv1+KIrqm0JDVvnq1+EZhIrinIqnxxV5+nb+KMSGmShgWhpkHVZfDrSlyqZvmYHsdZZwx7mKq/l7jx1vpxL+ZO8uodukyFPzKDh+hMQaEt4zb6AyBtdfohQ+Vq1vnroGX1XU7kgn/ZFTPa5JSx4RQoE78KaTrFdpGYzWj0DA0PfyNj1HzvjosS3C5fXsP7trM=
  file:
  - k8s
  on:
    repo: pathristikon/k8s-applier
    tags: false
    go: 1.11.x
