language: go
go:
- 1.11.x
- 1.12.x
- master

os:
  - linux
  - osx

script:
  - env GO111MODULE=on go build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: "k8s"
  on:
    repo: pathristikon/k8s-applier
    tags: true
    go: 1.11.x
